/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 frog.glb 
Author: yanix (https://sketchfab.com/yanix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tiny-frog-c25c8980b93a460aa521ae62d3d94e0e
Title: Tiny Frog
*/

import { useGLTF } from "@react-three/drei";

export function TinyFrogModel(props) {
  const { nodes, materials } = useGLTF("/models/frog.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.frog_frog_mat_0.geometry}
          material={materials.frog_mat}
          position={[-0.022, 5.203, -0.724]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          geometry={nodes.Plane_ground_0.geometry}
          material={materials.ground}
          position={[-0.014, 0.002, -0.46]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/frog.glb");
