/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 jousting-helmet.glb 
Author: The Royal Armoury (Livrustkammaren) (https://sketchfab.com/TheRoyalArmoury)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jousting-helmet-a4eea31d9d9441af9434a7da5ae46b54
Title: Jousting Helmet
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function JoustingHelmetModel(props) {
  const { nodes, materials } = useGLTF("models/jousting-helmet.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-2.016, -0.06, 1.381]}
        rotation={[-1.601, 0.068, 2.296]}
        scale={0.038}
      >
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.model_Material_u1_v1}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.model_Material_u1_v1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/jousting-helmet.glb");
