/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 maximelbv-logo.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MaximelbvLogoModel(props) {
  const { nodes, materials } = useGLTF("models/maximelbv-logo.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["Material.001"]}
        position={[-0.121, -0.062, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/maximelbv-logo.glb");
