/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 moto.glb 
Author: Jonrss (https://sketchfab.com/huy14320000006)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kawashaki-ninja-h2-73eebe213a3043d1a1eb277c8ce05b5f
Title: Kawashaki ninja h2
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function MotoModel(props) {
  const { nodes, materials } = useGLTF("/models/moto.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        >
          <mesh
            geometry={nodes["Mesh_0000rip_V���t_Li���u003_0"].geometry}
            material={materials["Vt_Liu.003"]}
          />
          <mesh
            geometry={nodes["Mesh_0000rip_V���t_Li���u002_0"].geometry}
            material={materials["Vt_Liu.002"]}
          />
        </group>
        <group
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        >
          <mesh
            geometry={nodes["Mesh_0166rip_V���t_Li���u016_0"].geometry}
            material={materials["Vt_Liu.016"]}
          />
          <mesh
            geometry={nodes["Mesh_0166rip_V���t_Li���u002_0"].geometry}
            material={materials["Vt_Liu.002"]}
          />
          <mesh
            geometry={nodes["Mesh_0166rip_V���t_Li���u006_0"].geometry}
            material={materials["Vt_Liu.006"]}
          />
          <mesh
            geometry={nodes["Mesh_0166rip_V���t_Li���u015_0"].geometry}
            material={materials["Vt_Liu.015"]}
          />
          <mesh
            geometry={nodes["Mesh_0166rip_V���t_Li���u_0"].geometry}
            material={materials.Vt_Liu}
          />
        </group>
        <group
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        >
          <mesh
            geometry={nodes["0000_Mesh_0170rip_V���t_Li���u011_0"].geometry}
            material={materials["Vt_Liu.011"]}
          />
          <mesh
            geometry={nodes["0000_Mesh_0170rip_V���t_Li���u017_0"].geometry}
            material={materials["Vt_Liu.017"]}
          />
          <mesh
            geometry={nodes["0000_Mesh_0170rip_V���t_Li���u007_0"].geometry}
            material={materials["Vt_Liu.007"]}
          />
          <mesh
            geometry={nodes["0000_Mesh_0170rip_V���t_Li���u006_0"].geometry}
            material={materials["Vt_Liu.006"]}
          />
          <mesh
            geometry={nodes["0000_Mesh_0170rip_V���t_Li���u018_0"].geometry}
            material={materials["Vt_Liu.018"]}
          />
        </group>
        <group
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        >
          <mesh
            geometry={nodes["0001_Mesh_0170rip_V���t_Li���u016_0"].geometry}
            material={materials["Vt_Liu.016"]}
          />
          <mesh
            geometry={nodes["0001_Mesh_0170rip_V���t_Li���u006_0"].geometry}
            material={materials["Vt_Liu.006"]}
          />
        </group>
        <mesh
          geometry={nodes.Mesh_0153rip__0.geometry}
          material={materials["Mesh_0153.rip__0"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes.Mesh_0162rip__0.geometry}
          material={materials["Mesh_0153.rip__0"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0023rip_V���t_Li���u021_0"].geometry}
          material={materials["Vt_Liu.021"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0126rip_V���t_Li���u008_0"].geometry}
          material={materials["Vt_Liu.008"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0016rip_V���t_Li���u001_0"].geometry}
          material={materials["Vt_Liu.001"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0119rip_V���t_Li���u008_0"].geometry}
          material={materials["Vt_Liu.008"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes.Mesh_0039rip__0.geometry}
          material={materials["Mesh_0153.rip__0"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0017rip_V���t_Li���u020_0"].geometry}
          material={materials["Vt_Liu.020"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0178rip_V���t_Li���u013_0"].geometry}
          material={materials["Vt_Liu.013"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0014rip_V���t_Li���u009_0"].geometry}
          material={materials["Vt_Liu.009"]}
          position={[-82.259, 29.987, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0123rip_V���t_Li���u015_0"].geometry}
          material={materials["Vt_Liu.015"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0010rip_V���t_Li���u005_0"].geometry}
          material={materials["Vt_Liu.005"]}
          position={[94.904, 32.788, 5.951]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0001rip_V���t_Li���u_0"].geometry}
          material={materials.Vt_Liu}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0009rip_V���t_Li���u005_0"].geometry}
          material={materials["Vt_Liu.005"]}
          position={[-82.267, 29.987, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0012rip_V���t_Li���u019_0"].geometry}
          material={materials["Vt_Liu.019"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0006rip_V���t_Li���u004_0"].geometry}
          material={materials["Vt_Liu.004"]}
          position={[-82.267, 29.987, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0005rip_V���t_Li���u001_0"].geometry}
          material={materials["Vt_Liu.001"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0007rip_V���t_Li���u004_0"].geometry}
          material={materials["Vt_Liu.004"]}
          position={[94.904, 32.788, 5.951]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0004rip_V���t_Li���u012_0"].geometry}
          material={materials["Vt_Liu.012"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["Mesh_0018rip_V���t_Li���u001_0"].geometry}
          material={materials["Vt_Liu.001"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
        <mesh
          geometry={nodes["0002_Mesh_0170rip_V���t_Li���u010_0"].geometry}
          material={materials["Vt_Liu.010"]}
          position={[6.341, -7.74, 6.223]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[-1.251, 1.251, 1.251]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/moto.glb");
